env:
  global:
  - DIST_DIR="${PWD}/dist"
  - PROJECT_NAME=$(basename ${PWD})
  - ARTIFACT_ID="${TRAVIS_COMMIT}-${TRAVIS_BUILD_NUMBER}"
  - S3_BUCKET="serverlessops-opensource-deploy-dev"
  - S3_BUILD_PREFIX="${PROJECT_NAME}/${ARTIFACT_ID}/build"
  - S3_DEPLOY_PREFIX="${PROJECT_NAME}/${ARTIFACT_ID}/deploy"
  - AWS_SAM_TMPL_NAME="sam-template.yml"
  - AWS_CFN_TMPL_NAME="cfn-template.yml"
  - AWS_DEFAULT_REGION="us-east-1"
  - secure: Kro65Ib69xjc2bonXGWiBRfQXvz6Eggh1wxeDbzgstn1nTyX8VCvQ7Px7eSWsoiki+y6C9A7ZPd4Zhv6ErnBrQ1CXunXNMqni+X430hfdUifjzOa7rRHPnSMKpewvWiCYdJKUtQjYc43hh2bZA4LyrzTfPa/gAHKvhT0nwlj8eZW2wzS6BT1pbEpqR2QipIXKzxsajTaWzB7+5RlEAcCcPf6IVJhmh1F+UbjCanNNKqttW62R98qPedqNwj6K27agWiAAuDXQam8SBPUD3DDspso+cE3BZ18ibupo0P9Z60/AF8L0giDpw0w4NDI7SyJo7h6fQxS/+Cwy4r1sC1kiSZOktIN4+HXogq79fM/9181X1mB4IiRHMy4yQlCD1sqhemcKB7dTmh8NSIuH2/eC/SxHixPyEjRQce1yVjsAEhobTJyqjtbLY9wqNV4nTqsjfe9/SCIlrKj80M0muAuAyekwB1e9Bc0HLUpNspkDic2ZnbMRPsQQsA5PcLImQ43lCS1n2gokSwO/TbLd+Fy9BLgOJjWouqls+EUwqdZSJuljwz1qO3U/9CAt7f+Yhx9RSGG91yxVXBJ6ZeDKL/XmGUPnRVgWauVuM94CbuD3c5bstjFLCEe09meOTTAUFnXBMqTKKV10pZsgxAE49O6Cw6qZMx/zhnUqNGG3qsOb1s=
  - secure: v2bzOImGqmpo5Ae/2Vw8ZqaZQU6LCOvC+td7ToHsNv6HtFWQMOEyVnpkTF8dTB5IHHwzUtjqigdH+1g3Ju56v0l7Of5t2xOuYGfLG9Md4Q3bHuboM0zgAfy6k9zoPTOJNRfl87dOOIsXBqgdzcti+TjLx9VAQ9DgPZzrcr60hu84XtegWqkNQazH63fuuZYvkkN3CGm9sXgOWGKRS6JtFDRoXMupglxyz/mJPiw0stDc/2i6j6VF27aRpQfdkWwrcouKUlwRmhbLUozHUpu+vf7ZBD/ze8SS+BjqvaaOBKSNOzdd2HqWEPsR8hy6XmkuvTAnJssFL1R/4YtpbxKREGBGVyhqbZ4xRC6ofhw9tSzwJi2teCYU34RNMTuIsMv0abeRVXWDxJRYHo1Ogf7D46R1anFen+lfyWmJuC5I1RMDDu/qLcCrveAwz9jYyXXT7fNFHSWhc4mgmiL9nRiYwI/wuBNx33+a7AwDNaHmaqaJh16BhXeWontXy07BBt1LxajgyzwYW0ZxJ2clVkcogMni0xXrgKnl94/G/SeEIRfxwNiwbuP5NdGJKrOmmBEMASqbS7szY1waxuKaWNhVThOOQLI4w9Ff7t2+SCxtqFfif1uOa1iSG3PNNjTfZzWa8sDNpeTAOnBh+Frm2qCxNoalsiwpwkhxYmGWjstxXr4=
stages:
- build
- artifact
- name: promote
  if: branch = master
jobs:
  include:
  - stage: build
    sudo: required
    services:
    - docker
    language: python
    python: '3.6'
    install:
    - npm install -g serverless
    - npm install
    script: skip
    before_deploy:
    - sls package -v -s dev -r us-east-1 -p $DIST_DIR
    - cp serverless.yml $DIST_DIR
    - rm -rf ${DIST_DIR}/requirements
    deploy:
    - provider: s3
      skip_cleanup: true
      bucket: "$S3_BUCKET"
      upload_dir: "${PROJECT_NAME}/${ARTIFACT_ID}/build"
      local_dir: "$DIST_DIR"
      acl: private
      on:
        repo: "$TRAVIS_REPO_SLUG"
      access_key_id: "$AWS_ACCESS_KEY_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  - stage: artifact
    language: python
    python: '3.6'
    install:
    - npm install -g serverless
    - npm install
    - pip install awscli
    script: skip
    before_deploy:
    - mkdir tmp
    - aws s3 cp s3://${S3_BUCKET}/${S3_BUILD_PREFIX}/${PROJECT_NAME}.zip ./
    - aws s3 cp s3://${S3_BUCKET}/${S3_BUILD_PREFIX}/serverless.yml ./tmp/
    - unzip ${PROJECT_NAME}.zip -d tmp
    - cd tmp
    - mkdir $DIST_DIR
    - sls sam export --output ${DIST_DIR}/${AWS_SAM_TMPL_NAME}
    - aws cloudformation package --template-file ${DIST_DIR}/${AWS_SAM_TMPL_NAME}
      --output-template-file ${DIST_DIR}/${AWS_CFN_TMPL_NAME} --s3-bucket ${S3_BUCKET}
      --s3-prefix ${S3_DEPLOY_PREFIX}
    deploy:
    - provider: s3
      skip_cleanup: true
      bucket: "$S3_BUCKET"
      upload_dir: "${PROJECT_NAME}/${ARTIFACT_ID}/deploy"
      local_dir: "$DIST_DIR"
      acl: public_read
      on:
        repo: "$TRAVIS_REPO_SLUG"
      access_key_id: "$AWS_ACCESS_KEY_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    after_deploy:
    - aws s3 cp --recursive --acl public-read s3://${S3_BUCKET}/${S3_DEPLOY_PREFIX}/
      s3://${S3_BUCKET}/${S3_DEPLOY_PREFIX}/
  - stage: promote
    language: python
    python: '3.6'
    install:
    - pip install awscli
    script: skip
    deploy:
    - provider: script
      script: aws s3api put-object --acl public-read --bucket $S3_BUCKET --key ${PROJECT_NAME}/CFN-DEPLOY-LATEST
        --website-redirect-location "https://console.aws.amazon.com/cloudformation/home?region=${AWS_DEFAULT_REGION}#/stacks/new?stackName=${PROJECT_NAME}&templateURL=https://${S3_BUCKET}.s3.amazonaws.com/${S3_DEPLOY_PREFIX}/${AWS_CFN_TMPL_NAME}"
        --cache-control "max-age=60"
      on:
        repo: "$TRAVIS_REPO_SLUG"
    - provider: script
      script: aws s3api put-object --acl public-read --bucket $S3_BUCKET --key ${PROJECT_NAME}/SAM-TEMPLATE-LATEST
        --website-redirect-location "https://${S3_BUCKET}.s3.amazonaws.com/${S3_DEPLOY_PREFIX}/${AWS_SAM_TMPL_NAME}"
        --cache-control "max-age=60"
      on:
        repo: "$TRAVIS_REPO_SLUG"
